plugins {
    id 'java'
    id 'idea'
    id 'eclipse'
    id 'net.minecraftforge.gradle' version '[7.0.3,8)'
}

version = project.mod_version
group = project.maven_group

base { archivesName = project.archives_base_name }

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
    withSourcesJar()
}

minecraft {
    mappings channel: 'official', version: project.minecraft_version

    runs {
        configureEach {
            workingDir = layout.projectDirectory.dir('run')
            args "--mixin.config=${project.mod_id}.mixins.json"
            systemProperty 'eventbus.api.strictRuntimeChecks', 'true'
            systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
        }

        register('client')
    }
}

repositories {
    minecraft.mavenizer(it)
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
    mavenCentral()
}

dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:${project.forge_version}")
    annotationProcessor 'net.minecraftforge:eventbus-validator:7.0.1'
}

processResources {
    inputs.property "version", project.version
    filesMatching("META-INF/mods.toml") { expand "version": project.version }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.named('jar', Jar) {
    manifest {
        attributes['MixinConfigs'] = "${project.mod_id}.mixins.json"
    }
}
