org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.20
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=atomics_client
mod_name=Atomics Client
mod_license=MIT
mod_version=1.3
mod_group_id=com.atomics
mod_authors=AtomicSky1
mod_description=Atomics Client is a mod that provides some nice QOL features for PvP
